development:
  adapter: postgresql
  encoding: unicode
  database: angshake_dev
  pool: 100
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: angshake_test
  pool: 10
  timeout: 5000
  username: 
  password: